### ISSUE TITLE
Re-enable evaluation script in CI once it is fast enough

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/specimin#121]
> The CI fails at the evaluation script step. I am not sure why. This discussion in this GitHub https://github.com/actions/runner-images/issues/6680 seems to be suggesting that we have reached the CPU limitations.

This is almost certainly a resource limitation issue on GitHub's side: our job is using too many resources, so it is being cancelled. We need to either reduce the amount of work that Specimin does, parallelize this job, or split up the evaluation job into multiple parts.

@LoiNguyenCS I know you've said you have some ideas about improving Specimin's performance by reducing the amount of I/O that it does. I think this problem is a good incentive to spending an hour or two investigating whether there is an easy win there.

@tahiat have you made any progress looking into parallelizing the evaluation of these builds using pash, as we discussed a few weeks ago? If we can land that, it would probably fix this problem, too.

_Originally posted by @kelloggm in https://github.com/kelloggm/specimin/issues/119#issuecomment-1944422669_

**Comment by kelloggm** [comment]
In #119 we disabled the evaluation script running on each CI job, because it is too slow.

**Comment by LoiNguyenCS** [comment]
The CI is re-enabled after merging #123.
