### ISSUE TITLE
Not Minimizing a Specific Method - Gets Stuck at Run (Urgent)

### ISSUE THREAD

**Issue by jonathan-m-phillips** [kelloggm/specimin#87]
When running Specimin on `org.checkerframework.dataflow.analysis.AbstractAnalysis#getCurrentTree()` the process just runs without minimizing, throwing an exception, completing, or exiting in anyway. I tried multiple times and one time waited for over 5 minutes before terminating the process.

Link to the method: [AbstractAnalysis#getCurrentTree()](https://github.com/typetools/checker-framework/blob/master/dataflow/src/main/java/org/checkerframework/dataflow/analysis/AbstractAnalysis.java)

I find this issue to be **urgent** because ASHE can drynrun and iterate over exceptions thrown by Specimin, but if we are getting hung up on issues like this, there is no way to bypass but to manually force a skip of this method (hardcode it). This is not the best solution. There might be more methods that get hung up that we are unaware currently.

`./gradlew run --args='--outputDirectory "tempDir" --root "/my/absolute/path/checker-framework/dataflow/src/main/java" --targetFile "org/checkerframework/dataflow/analysis/AbstractAnalysis.java" --targetMethod "org.checkerframework.dataflow.analysis.AbstractAnalysis#getCurrentTree()"'`

There is a chance I am just calling this method incorrectly. If so, please let me know!

**Comment by jonathan-m-phillips** [comment]
I am currently looking into this issue.

**Comment by LoiNguyenCS** [comment]
@jonathan-m-phillips 

> This appears to be an infinite loop when trying to minimize. I believe we are visiting each field and method within the class unlimited amounts of times

I think this is due to `UnsolvedSymbolVisitor` can not create synthetic classes to solve some unsolved symbols in the input file. `UnsolvedSymbolVisitor` only stops when all the symbols in the input file are solved.

> Also, @LoiNguyenCS, does the following missing classes seem like normal behavior? These are just a few examples.

Yes, there are correct. The names of those synthetic types look quite long, but it helps to avoid unwanted duplications.

**Comment by kelloggm** [comment]
@jonathan-m-phillips #91, which was just merged, might help with this (and you should merge from `main` before you continue debugging so that you're using it): it will remove the `<V, S, T>` in the middle of these class names. At the very least, it should make this easier to debug.

**Comment by LoiNguyenCS** [comment]
Oh, I've made a mistake. There should not be any `<V, S, T>` in the middle of these class names.

I will make a PR to address this problem, since #91 only remove the generic types when handling file paths.

**Comment by kelloggm** [comment]
@LoiNguyenCS I've found a small test case that triggers this loop. It's on the branch `outer-class-field`, which is named incorrectly (sorry).

The key problem is that the input file contains usages of an interface that is not a target file but is available as source (`org.checkerframework.dataflow.cfg.block.Block`. This interface extends another interface, which is from a library: `org.plumelib.util.UniqueId`. I suspect that there's some issue in how we handle interfaces that causes this problem, but I'm not sure what it is (and I have no more time to debug today). If you know what's wrong, I'd appreciate it if you'd implement a fix; if not, I can look into more deeply later this week.

**Comment by LoiNguyenCS** [comment]
>  If you know what's wrong, I'd appreciate it if you'd implement a fix; if not, I can look into more deeply later this week.

I have found a fix for that. It happens because `Block` is not added as a target file, which leads to `UniqueId` never be solved by `UnsolvedSymbolVisitor`.

**Comment by kelloggm** [comment]
> I have found a fix for that. It happens because Block is not added as a target file, which leads to UniqueId never be solved by UnsolvedSymbolVisitor.

I don't think Block needs to be a target file - there's no need to preserve UniqueId, because it (and its associated methods) are never used in the actual target class. We do need a synthetic class for `Block`, but that synthetic class doesn't need to implement UniqueId (I think).

**Comment by LoiNguyenCS** [comment]
Professor, 

>  We do need a synthetic class for Block, but that synthetic class doesn't need to implement UniqueId (I think).

In your test case, `Block` is in the original input. Creating a synthetic class for a class originally present in the input is risky, as it could lead to the loss of additional data from the class that might be utilized by other classes.

So I think it's better to add `Block` to the list of target files and create a synthetic class for `UniqueId`, or we can modify `PrunerVisitor` to remove the `extends UniqueId` part from the declaration of `Block`, just like how we handle unsolved interfaces.

(As I understand, creating a synthetic class is writing a new class from scratch, similar to how we handle imported classes from external libraries. Please let me know if I am misunderstanding you.)

**Comment by LoiNguyenCS** [comment]
Professor,

> we can modify PrunerVisitor to remove the extends UniqueId part from the declaration of Block

By testing, I've realized that this is quite difficult to do. Given your test case in #107, class B and its associate methods and fields are not used in the target method, but if we remove the "extends B" part in the declaration of class A, we will have a compilation issue.

> If UniqueId is preserved as a synthetic class, that's okay

So I think we should adapt this solution, which is more much easier.

**Comment by kelloggm** [comment]
> If UniqueId is preserved as a synthetic class, that's okay
> So I think we should adapt this solution, which is much easier

Sounds good to me.

**Comment by kelloggm** [comment]
Fixed by #114.
